version: '3'

services:
  app:
    container_name: Study_English-app
    build: ./frontend
    restart: unless-stopped
    volumes: 
      - ~/.logs/:/app/logs/
    ports: 
      - ${PORT}:${PORT}
    env_file: ./.env
    

  web:
    container_name: Study_English-web
    image: nginx
    restart: unless-stopped
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      #- ./nginx/nginx.template:/etc/nginx/conf.d/nginx.template
      - ./frontend/build/:/usr/share/nginx/html/
    depends_on:
      - app
    env_file:
      - ./.env
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
